window.mt = window.mt || {}; window.mt.data = {
	"assets": {
		"name": "assets",
		"contents": [
			{
				"name": "Loading",
				"contents": [
					{
						"id": 2,
						"name": "loading.png",
						"fullPath": "/Loading/loading.png",
						"key": "/preload.png",
						"width": 190,
						"height": 9,
						"frameWidth": 190,
						"frameHeight": 9,
						"frameMax": -1,
						"margin": 0,
						"spacing": 0,
						"anchorX": 0,
						"anchorY": 0,
						"fps": 10,
						"updated": 1406817917030,
						"atlas": ""
					},
					{
						"id": 1,
						"name": "preload.png",
						"fullPath": "/Loading/preload.png",
						"key": "/loading.png",
						"width": 190,
						"height": 9,
						"frameWidth": 190,
						"frameHeight": 9,
						"frameMax": -1,
						"margin": 0,
						"spacing": 0,
						"anchorX": 0,
						"anchorY": 0,
						"fps": 10,
						"updated": 1406817915033,
						"atlas": ""
					}
				],
				"count": 0,
				"id": 4,
				"fullPath": "/Loading",
				"isClosed": true
			},
			{
				"id": "launcher",
				"name": "launcher.png",
				"fullPath": "/launcher.png",
				"key": "/launcher.png",
				"width": 128,
				"height": 128,
				"frameWidth": 128,
				"frameHeight": 128,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1406817915034,
				"atlas": ""
			},
			{
				"id": "a5028e6d-7144-49ab-8fe1-5aefc9e899a9",
				"name": "player.png",
				"fullPath": "/player.png",
				"key": "/player.png",
				"width": 50,
				"height": 55,
				"frameWidth": 50,
				"frameHeight": 55,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1475263281812,
				"atlas": ""
			},
			{
				"id": "132759a0-cad6-4061-b0d2-55fe149c127e",
				"name": "ground.png",
				"fullPath": "/ground.png",
				"key": "/ground.png",
				"width": 50,
				"height": 50,
				"frameWidth": 50,
				"frameHeight": 50,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1475264486139,
				"atlas": ""
			},
			{
				"id": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
				"name": "dirt.png",
				"fullPath": "/dirt.png",
				"key": "/dirt.png",
				"width": 50,
				"height": 50,
				"frameWidth": 50,
				"frameHeight": 50,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1475264489226,
				"atlas": ""
			},
			{
				"id": "ff667d5d-56ea-4be8-aebe-fdb372b3cf72",
				"name": "Box.png",
				"fullPath": "/Box.png",
				"key": "/Box.png",
				"width": 50,
				"height": 50,
				"frameWidth": 50,
				"frameHeight": 50,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1475264492380,
				"atlas": ""
			}
		],
		"count": 8
	},
	"objects": {
		"name": "objects",
		"contents": [
			{
				"assetId": "ff667d5d-56ea-4be8-aebe-fdb372b3cf72",
				"x": 600,
				"y": 700,
				"type": 0,
				"anchorX": 0.5,
				"anchorY": 0.5,
				"userData": {},
				"physics": {
					"enable": 1,
					"immovable": 0,
					"bounce": {
						"x": 0,
						"y": 0
					},
					"gravity": {
						"allow": 1,
						"x": 0,
						"y": 0
					},
					"size": {
						"width": -1,
						"height": -1,
						"offsetX": 0,
						"offsetY": 0
					},
					"rotation": {
						"allowRotation": 0,
						"maxAngular": 0
					},
					"maxVelocity": 0,
					"mass": 100,
					"collideWorldBounds": 0
				},
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"contents": [],
				"width": 50,
				"height": 50,
				"id": "tmp1475694448392",
				"name": "CursorBox",
				"index": -1,
				"fullPath": "/CursorBox",
				"isClosed": true,
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				},
				"assetKey": "/Box.png"
			},
			{
				"id": "tmp1480625835462",
				"name": "Draggable",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "ff667d5d-56ea-4be8-aebe-fdb372b3cf72",
						"x": 100,
						"y": 800,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0,
							"immovable": 1,
							"bounce": {
								"x": 0,
								"y": 0
							},
							"gravity": {
								"allow": 1,
								"x": 0,
								"y": 0
							},
							"size": {
								"width": -1,
								"height": -1,
								"offsetX": 0,
								"offsetY": 0
							},
							"rotation": {
								"allowRotation": 0,
								"maxAngular": 0
							},
							"maxVelocity": 0,
							"mass": 100,
							"collideWorldBounds": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1480625835464",
						"name": "Box1",
						"index": -1,
						"fullPath": "/Draggable/Box1",
						"isClosed": true,
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/Box.png"
					},
					{
						"assetId": "ff667d5d-56ea-4be8-aebe-fdb372b3cf72",
						"x": 150,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0,
							"immovable": 1,
							"bounce": {
								"x": 0,
								"y": 0
							},
							"gravity": {
								"allow": 1,
								"x": 0,
								"y": 0
							},
							"size": {
								"width": -1,
								"height": -1,
								"offsetX": 0,
								"offsetY": 0
							},
							"rotation": {
								"allowRotation": 0,
								"maxAngular": 0
							},
							"maxVelocity": 0,
							"mass": 100,
							"collideWorldBounds": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1480625835466",
						"name": "Box2",
						"index": -1,
						"fullPath": "/Draggable/Box2",
						"isClosed": true,
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/Box.png"
					},
					{
						"assetId": "ff667d5d-56ea-4be8-aebe-fdb372b3cf72",
						"x": 100,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0,
							"immovable": 1,
							"bounce": {
								"x": 0,
								"y": 0
							},
							"gravity": {
								"allow": 1,
								"x": 0,
								"y": 0
							},
							"size": {
								"width": -1,
								"height": -1,
								"offsetX": 0,
								"offsetY": 0
							},
							"rotation": {
								"allowRotation": 0,
								"maxAngular": 0
							},
							"maxVelocity": 0,
							"mass": 100,
							"collideWorldBounds": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402644",
						"name": "Box",
						"index": -1,
						"fullPath": "/Draggable/Box",
						"isClosed": true,
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/Box.png"
					}
				],
				"isVisible": 1,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/Draggable",
				"physics": {
					"enable": 1,
					"immovable": 0,
					"bounce": {
						"x": 0,
						"y": 0
					},
					"gravity": {
						"allow": 1,
						"x": 0,
						"y": 500
					},
					"size": {
						"width": -1,
						"height": -1,
						"offsetX": 0,
						"offsetY": 0
					},
					"rotation": {
						"allowRotation": 0,
						"maxAngular": 0
					},
					"maxVelocity": 0,
					"mass": 1,
					"collideWorldBounds": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1475696361846",
				"name": "bullets",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [],
				"isVisible": 1,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/bullets",
				"physics": {
					"enable": 1,
					"immovable": 0,
					"bounce": {
						"x": 1,
						"y": 1
					},
					"gravity": {
						"allow": 1,
						"x": 0,
						"y": 0
					},
					"size": {
						"width": -1,
						"height": -1,
						"offsetX": 0,
						"offsetY": 0
					},
					"rotation": {
						"allowRotation": 0,
						"maxAngular": 0
					},
					"maxVelocity": 0,
					"mass": 1,
					"collideWorldBounds": 1
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1475263402607",
				"name": "dirt",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 950,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402739",
						"name": "dirt6",
						"index": -1,
						"fullPath": "/dirt/dirt6",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 950,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402740",
						"name": "dirt7",
						"index": -1,
						"fullPath": "/dirt/dirt7",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 950,
						"y": 850,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402738",
						"name": "dirt5",
						"index": -1,
						"fullPath": "/dirt/dirt5",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 900,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402737",
						"name": "dirt4",
						"index": -1,
						"fullPath": "/dirt/dirt4",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 950,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402736",
						"name": "dirt3",
						"index": -1,
						"fullPath": "/dirt/dirt3",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1550,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402735",
						"name": "dirt2",
						"index": -1,
						"fullPath": "/dirt/dirt2",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1550,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402734",
						"name": "dirt1",
						"index": -1,
						"fullPath": "/dirt/dirt1",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1500,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402731",
						"name": "dirt49",
						"index": -1,
						"fullPath": "/dirt/dirt49",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1550,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402732",
						"name": "dirt50",
						"index": -1,
						"fullPath": "/dirt/dirt50",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1500,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402730",
						"name": "dirt48",
						"index": -1,
						"fullPath": "/dirt/dirt48",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1500,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402729",
						"name": "dirt47",
						"index": -1,
						"fullPath": "/dirt/dirt47",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1550,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402711",
						"name": "dirt46",
						"index": -1,
						"fullPath": "/dirt/dirt46",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1450,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402707",
						"name": "dirt44",
						"index": -1,
						"fullPath": "/dirt/dirt44",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1500,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402708",
						"name": "dirt45",
						"index": -1,
						"fullPath": "/dirt/dirt45",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1400,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402706",
						"name": "dirt43",
						"index": -1,
						"fullPath": "/dirt/dirt43",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1350,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402705",
						"name": "dirt42",
						"index": -1,
						"fullPath": "/dirt/dirt42",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1300,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402704",
						"name": "dirt41",
						"index": -1,
						"fullPath": "/dirt/dirt41",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1250,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402703",
						"name": "dirt40",
						"index": -1,
						"fullPath": "/dirt/dirt40",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1200,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402702",
						"name": "dirt39",
						"index": -1,
						"fullPath": "/dirt/dirt39",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1150,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402701",
						"name": "dirt38",
						"index": -1,
						"fullPath": "/dirt/dirt38",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1100,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402700",
						"name": "dirt37",
						"index": -1,
						"fullPath": "/dirt/dirt37",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1000,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402699",
						"name": "dirt36",
						"index": -1,
						"fullPath": "/dirt/dirt36",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 1050,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402698",
						"name": "dirt35",
						"index": -1,
						"fullPath": "/dirt/dirt35",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 950,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402697",
						"name": "dirt34",
						"index": -1,
						"fullPath": "/dirt/dirt34",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 900,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402696",
						"name": "dirt33",
						"index": -1,
						"fullPath": "/dirt/dirt33",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 850,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402695",
						"name": "dirt32",
						"index": -1,
						"fullPath": "/dirt/dirt32",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 800,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402694",
						"name": "dirt31",
						"index": -1,
						"fullPath": "/dirt/dirt31",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 700,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402636",
						"name": "dirt28",
						"index": -1,
						"fullPath": "/dirt/dirt28",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 650,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402634",
						"name": "dirt26",
						"index": -1,
						"fullPath": "/dirt/dirt26",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 750,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402638",
						"name": "dirt30",
						"index": -1,
						"fullPath": "/dirt/dirt30",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 600,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402632",
						"name": "dirt24",
						"index": -1,
						"fullPath": "/dirt/dirt24",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 700,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402635",
						"name": "dirt27",
						"index": -1,
						"fullPath": "/dirt/dirt27",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 650,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402633",
						"name": "dirt25",
						"index": -1,
						"fullPath": "/dirt/dirt25",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 550,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402631",
						"name": "dirt23",
						"index": -1,
						"fullPath": "/dirt/dirt23",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 500,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402630",
						"name": "dirt22",
						"index": -1,
						"fullPath": "/dirt/dirt22",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 450,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402628",
						"name": "dirt20",
						"index": -1,
						"fullPath": "/dirt/dirt20",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 450,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402629",
						"name": "dirt21",
						"index": -1,
						"fullPath": "/dirt/dirt21",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 450,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402627",
						"name": "dirt19",
						"index": -1,
						"fullPath": "/dirt/dirt19",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 450,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402626",
						"name": "dirt18",
						"index": -1,
						"fullPath": "/dirt/dirt18",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 450,
						"y": 850,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402625",
						"name": "dirt17",
						"index": -1,
						"fullPath": "/dirt/dirt17",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 400,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402624",
						"name": "dirt16",
						"index": -1,
						"fullPath": "/dirt/dirt16",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 400,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402622",
						"name": "dirt14",
						"index": -1,
						"fullPath": "/dirt/dirt14",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 400,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402620",
						"name": "dirt12",
						"index": -1,
						"fullPath": "/dirt/dirt12",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 400,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402621",
						"name": "dirt13",
						"index": -1,
						"fullPath": "/dirt/dirt13",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 350,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402623",
						"name": "dirt15",
						"index": -1,
						"fullPath": "/dirt/dirt15",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 350,
						"y": 850,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402616",
						"name": "dirt8",
						"index": -1,
						"fullPath": "/dirt/dirt8",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 350,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402618",
						"name": "dirt10",
						"index": -1,
						"fullPath": "/dirt/dirt10",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 400,
						"y": 850,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402619",
						"name": "dirt11",
						"index": -1,
						"fullPath": "/dirt/dirt11",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 300,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402614",
						"name": "dirt6",
						"index": -1,
						"fullPath": "/dirt/dirt6",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 350,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402617",
						"name": "dirt9",
						"index": -1,
						"fullPath": "/dirt/dirt9",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 250,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402613",
						"name": "dirt5",
						"index": -1,
						"fullPath": "/dirt/dirt5",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 350,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402615",
						"name": "dirt7",
						"index": -1,
						"fullPath": "/dirt/dirt7",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 200,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402612",
						"name": "dirt4",
						"index": -1,
						"fullPath": "/dirt/dirt4",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 150,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402611",
						"name": "dirt3",
						"index": -1,
						"fullPath": "/dirt/dirt3",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 100,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402610",
						"name": "dirt2",
						"index": -1,
						"fullPath": "/dirt/dirt2",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 50,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402609",
						"name": "dirt1",
						"index": -1,
						"fullPath": "/dirt/dirt1",
						"movies": {},
						"assetKey": "/dirt.png"
					},
					{
						"assetId": "792ca4d1-a883-4ec8-a15a-7b7ceb6f3c59",
						"x": 0,
						"y": 1050,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402608",
						"name": "dirt",
						"index": -1,
						"fullPath": "/dirt/dirt",
						"movies": {},
						"assetKey": "/dirt.png"
					}
				],
				"isVisible": 1,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/dirt",
				"physics": {
					"enable": 1,
					"immovable": 1,
					"bounce": {
						"x": 1,
						"y": 1
					},
					"gravity": {
						"allow": 1,
						"x": 0,
						"y": 0
					},
					"size": {
						"width": -1,
						"height": -1,
						"offsetX": 0,
						"offsetY": 0
					},
					"rotation": {
						"allowRotation": 0,
						"maxAngular": 0
					},
					"maxVelocity": 0,
					"mass": 1,
					"collideWorldBounds": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1475263402605",
				"name": "ground",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2950,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262942",
						"name": "ground61",
						"index": -1,
						"fullPath": "/ground/ground61",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2900,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262941",
						"name": "ground60",
						"index": -1,
						"fullPath": "/ground/ground60",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2850,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262940",
						"name": "ground59",
						"index": -1,
						"fullPath": "/ground/ground59",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2750,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262939",
						"name": "ground58",
						"index": -1,
						"fullPath": "/ground/ground58",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2650,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262938",
						"name": "ground57",
						"index": -1,
						"fullPath": "/ground/ground57",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2700,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262937",
						"name": "ground56",
						"index": -1,
						"fullPath": "/ground/ground56",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2600,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262936",
						"name": "ground55",
						"index": -1,
						"fullPath": "/ground/ground55",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2550,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262935",
						"name": "ground54",
						"index": -1,
						"fullPath": "/ground/ground54",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2400,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262934",
						"name": "ground53",
						"index": -1,
						"fullPath": "/ground/ground53",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2400,
						"y": 900,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262933",
						"name": "ground52",
						"index": -1,
						"fullPath": "/ground/ground52",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2050,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262932",
						"name": "ground51",
						"index": -1,
						"fullPath": "/ground/ground51",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2500,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262931",
						"name": "ground50",
						"index": -1,
						"fullPath": "/ground/ground50",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2450,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262930",
						"name": "ground49",
						"index": -1,
						"fullPath": "/ground/ground49",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2400,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262929",
						"name": "ground48",
						"index": -1,
						"fullPath": "/ground/ground48",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2300,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262928",
						"name": "ground47",
						"index": -1,
						"fullPath": "/ground/ground47",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2350,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262927",
						"name": "ground46",
						"index": -1,
						"fullPath": "/ground/ground46",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2250,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262926",
						"name": "ground45",
						"index": -1,
						"fullPath": "/ground/ground45",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2200,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262925",
						"name": "ground44",
						"index": -1,
						"fullPath": "/ground/ground44",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2150,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262924",
						"name": "ground43",
						"index": -1,
						"fullPath": "/ground/ground43",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2100,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262923",
						"name": "ground42",
						"index": -1,
						"fullPath": "/ground/ground42",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2000,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262922",
						"name": "ground41",
						"index": -1,
						"fullPath": "/ground/ground41",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 2050,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262921",
						"name": "ground40",
						"index": -1,
						"fullPath": "/ground/ground40",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1950,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262920",
						"name": "ground39",
						"index": -1,
						"fullPath": "/ground/ground39",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1900,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262919",
						"name": "ground38",
						"index": -1,
						"fullPath": "/ground/ground38",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1850,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262918",
						"name": "ground37",
						"index": -1,
						"fullPath": "/ground/ground37",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1800,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262917",
						"name": "ground36",
						"index": -1,
						"fullPath": "/ground/ground36",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1750,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262916",
						"name": "ground35",
						"index": -1,
						"fullPath": "/ground/ground35",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1700,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262915",
						"name": "ground34",
						"index": -1,
						"fullPath": "/ground/ground34",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1650,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262914",
						"name": "ground33",
						"index": -1,
						"fullPath": "/ground/ground33",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1600,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1490044262913",
						"name": "ground32",
						"index": -1,
						"fullPath": "/ground/ground32",
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1550,
						"y": 850,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402728",
						"name": "ground2",
						"index": -1,
						"fullPath": "/ground/ground2",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1500,
						"y": 850,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402727",
						"name": "ground1",
						"index": -1,
						"fullPath": "/ground/ground1",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1400,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402724",
						"name": "ground28",
						"index": -1,
						"fullPath": "/ground/ground28",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1450,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402725",
						"name": "ground29",
						"index": -1,
						"fullPath": "/ground/ground29",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1350,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402723",
						"name": "ground27",
						"index": -1,
						"fullPath": "/ground/ground27",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1300,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402722",
						"name": "ground26",
						"index": -1,
						"fullPath": "/ground/ground26",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1200,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402721",
						"name": "ground25",
						"index": -1,
						"fullPath": "/ground/ground25",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1250,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402720",
						"name": "ground24",
						"index": -1,
						"fullPath": "/ground/ground24",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1150,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402719",
						"name": "ground23",
						"index": -1,
						"fullPath": "/ground/ground23",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1100,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402718",
						"name": "ground22",
						"index": -1,
						"fullPath": "/ground/ground22",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1050,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402717",
						"name": "ground21",
						"index": -1,
						"fullPath": "/ground/ground21",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 1000,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402716",
						"name": "ground20",
						"index": -1,
						"fullPath": "/ground/ground20",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 950,
						"y": 800,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402715",
						"name": "ground19",
						"index": -1,
						"fullPath": "/ground/ground19",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 900,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402714",
						"name": "ground18",
						"index": -1,
						"fullPath": "/ground/ground18",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 850,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402713",
						"name": "ground17",
						"index": -1,
						"fullPath": "/ground/ground17",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 800,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402712",
						"name": "ground16",
						"index": -1,
						"fullPath": "/ground/ground16",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"id": "tmp1475263402606",
						"name": "Group",
						"x": 0,
						"y": 0,
						"type": 1,
						"angle": 0,
						"contents": [],
						"isVisible": 1,
						"isLocked": 0,
						"isFixedToCamera": 0,
						"isClosed": 0,
						"scaleX": 1,
						"scaleY": 1,
						"alpha": 1,
						"fullPath": "/ground/Group"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 0,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402588",
						"name": "ground",
						"index": -1,
						"fullPath": "/ground/ground",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 700,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402604",
						"name": "ground15",
						"index": -1,
						"fullPath": "/ground/ground15",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 600,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402601",
						"name": "ground12",
						"index": -1,
						"fullPath": "/ground/ground12",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 650,
						"y": 950,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402602",
						"name": "ground13",
						"index": -1,
						"fullPath": "/ground/ground13",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 550,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402600",
						"name": "ground11",
						"index": -1,
						"fullPath": "/ground/ground11",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 750,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402603",
						"name": "ground14",
						"index": -1,
						"fullPath": "/ground/ground14",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 200,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402592",
						"name": "ground4",
						"index": -1,
						"fullPath": "/ground/ground4",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 100,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402590",
						"name": "ground2",
						"index": -1,
						"fullPath": "/ground/ground2",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 300,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402594",
						"name": "ground6",
						"index": -1,
						"fullPath": "/ground/ground6",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 50,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402589",
						"name": "ground1",
						"index": -1,
						"fullPath": "/ground/ground1",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 500,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402599",
						"name": "ground10",
						"index": -1,
						"fullPath": "/ground/ground10",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 450,
						"y": 800,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402598",
						"name": "ground9",
						"index": -1,
						"fullPath": "/ground/ground9",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 250,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402593",
						"name": "ground5",
						"index": -1,
						"fullPath": "/ground/ground5",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 400,
						"y": 800,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402597",
						"name": "ground8",
						"index": -1,
						"fullPath": "/ground/ground8",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 150,
						"y": 1000,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402591",
						"name": "ground3",
						"index": -1,
						"fullPath": "/ground/ground3",
						"movies": {},
						"assetKey": "/ground.png"
					},
					{
						"assetId": "132759a0-cad6-4061-b0d2-55fe149c127e",
						"x": 350,
						"y": 800,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 50,
						"height": 50,
						"id": "tmp1475263402596",
						"name": "ground7",
						"index": -1,
						"fullPath": "/ground/ground7",
						"movies": {},
						"assetKey": "/ground.png"
					}
				],
				"isVisible": 1,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/ground",
				"physics": {
					"enable": 1,
					"immovable": 1,
					"bounce": {
						"x": 1,
						"y": 1
					},
					"gravity": {
						"allow": 1,
						"x": 0,
						"y": 0
					},
					"size": {
						"width": -1,
						"height": -1,
						"offsetX": 0,
						"offsetY": 0
					},
					"rotation": {
						"allowRotation": 0,
						"maxAngular": 0
					},
					"maxVelocity": 0,
					"mass": 1,
					"collideWorldBounds": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"assetId": "a5028e6d-7144-49ab-8fe1-5aefc9e899a9",
				"x": 37.14285714285714,
				"y": 775.7142857142856,
				"type": 0,
				"anchorX": 0.4714285714285714,
				"anchorY": 0.5259740259740259,
				"userData": {},
				"physics": {
					"enable": 1,
					"immovable": 0,
					"bounce": {
						"x": 0.3,
						"y": 0.3
					},
					"gravity": {
						"allow": 1,
						"x": 0,
						"y": 550
					},
					"size": {
						"width": -1,
						"height": -1,
						"offsetX": 0,
						"offsetY": 0
					},
					"rotation": {
						"allowRotation": 1,
						"maxAngular": 0
					},
					"maxVelocity": 0,
					"mass": 1,
					"collideWorldBounds": 0
				},
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"contents": [],
				"width": 50,
				"height": 55,
				"id": "tmp1475263259226",
				"name": "player",
				"index": -1,
				"fullPath": "/player",
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				},
				"assetKey": "/player.png"
			},
			{
				"id": "tmp1406818026618",
				"name": "Loading",
				"x": 0,
				"y": 0,
				"angle": 0,
				"contents": [
					{
						"assetId": 2,
						"x": 256,
						"y": 192,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"width": 190,
						"height": 9,
						"id": "tmp1406818026617",
						"name": "preload",
						"fullPath": "/Loading/preload",
						"contents": [],
						"assetKey": "/preload.png"
					},
					{
						"assetId": 1,
						"x": 256,
						"y": 192,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"width": 190,
						"height": 9,
						"id": "tmp1406818026616",
						"name": "loading",
						"fullPath": "/Loading/loading",
						"contents": [],
						"assetKey": "/loading.png"
					}
				],
				"isVisible": false,
				"isLocked": true,
				"isFixedToCamera": 0,
				"fullPath": "/Loading",
				"isClosed": true,
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				},
				"type": 1
			}
		],
		"count": 0
	},
	"map": {
		"cameraX": 721,
		"cameraY": 187,
		"worldWidth": 10000,
		"worldHeight": 1080,
		"viewportWidth": 1920,
		"viewportHeight": 1080,
		"scaleMode": "SHOW_ALL",
		"gridX": 50,
		"gridY": 50,
		"gridOffsetX": 0,
		"gridOffsetY": 0,
		"showGrid": 1,
		"gridOpacity": 0.5000000000000002,
		"backgroundColor": "#1ca6c7",
		"movieInfo": {
			"fps": 60,
			"lastFrame": 60
		},
		"pixelPerfectPicking": 1,
		"physics": {
			"enable": 0
		}
	}
};
